language: node_js
node_js:
  - 10

before_install:
  - npm i -g npm
  - npm i -g mocha-only-detector
  - find test/ -name "*.js" -print0 | xargs -0 mocha-only-detector

env:
  global:
    - COVERAGE_BRANCH=master

jobs:
  include:
    - env:
        - TEST_PART: Sol6
    - env:
        - TEST_PART: Coverage

install:
  - npm ci

before_script:
  - npx solhint "contracts/sol6/**/*.sol"

script:
  - ./cmp.sh
  - .travis/test-part.sh
  - ./travis/report.sh
  